spring:
  config:
    import: application-secret.yml

  datasource:
    url: jdbc:mysql://junsub-dev.ctaka20akw4u.ap-northeast-2.rds.amazonaws.com/MY_MEMORY_SPACE
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace

#server:
#  servlet:
#    session:
#      timeout: 300m
#      cookie:
#        max-age: 300m